app.config(['$stateProvider',function($stateProvider){
	$stateProvider
	.state('admin',{
		url:'/admin',
		templateUrl:'views/admin.html',
		controller:'admin'
	})
	.state('slogin',{
		url:'/slogin',
		templateUrl:'views/slogin.html',
		controller:'slogin'
	})
	.state('flogin',{
		url:'/flogin',
		templateUrl:'views/flogin.html',
		controller:'flogin'
	})
	.state('shome',{
		url:'/home',
		controller:'shome',
		templateUrl:'views/home.html'
		
	})
	.state('fhome',{
		url:'/home',
		controller:'fhome',
		templateUrl:'views/home.html'
		
	})
	.state('defaultloc',{
		url:'/defaultloc',
		templateUrl:'views/defaultloc.html',
		controller:'defaultloc'
	})
	.state('admininsert',{
		url:'/admininsert',
		templateUrl:'views/admininsert.html',
		controller:'admininsert'
	})
	.state('sregister',{
		url:'/sregister',
		templateUrl:'views/sregister.html',
		controller:'sregister'
	})
	.state('fregister',{
		url:'/fregister',
		templateUrl:'views/fregister.html',
		controller:'fregister'
	})
	.state('aregister',{
		url:'/aregister',
		templateUrl:'views/aregister.html',
		controller:'aregister'
	})

	.state('adminSentry',{
		url:'/adminSentry',
		templateUrl:'views/adminSentry.html',
		controller:'adminSentry'
	})
	.state('adminFentry',{
		url:'/adminFentry',
		templateUrl:'views/adminFentry.html',
		controller:'adminFentry'
	})
	.state('adminSedit',{
		url:'/adminSedit',
		templateUrl:'views/adminSedit.html',
		controller:'adminSedit'
	})
	.state('adminFedit',{
		url:'/adminFedit',
		templateUrl:'views/adminFedit.html',
		controller:'adminFedit'
	})
	.state('busno66',{
		url:'/busno66',
		templateUrl:'views/busno66.html',
		controller:'busno66'
	})
	.state('busno1',{
		url:'/busno1',
		templateUrl:'views/busno1.html',
		controller:'busno1'
	})
	.state('busno2',{
		url:'/busno2',
		templateUrl:'views/busno2.html',
		controller:'busno2'
	})
	.state('busno3',{
		url:'/busno3',
		templateUrl:'views/busno3.html',
		controller:'busno3'
	})
	.state('busno4',{
		url:'/busno4',
		templateUrl:'views/busno4.html',
		controller:'busno4'
	})
	.state('busno5',{
		url:'/busno5',
		templateUrl:'views/busno5.html',
		controller:'busno5'
	})
	.state('about',{
		url:'/about',
		templateUrl:'views/about.html',
		controller:'about'
	})
	.state('busdetails',{
		url:'/busdetails',
		templateUrl:'views/busdetails.html',
		controller:'busdetails'
	})
	.state('home',{
		url:'/home',
		templateUrl:'views/home.html',
		controller:'home'
	})
	.state('root',{
		url:'/',
		templateUrl:'views/home.html',
		controller:'home'
	})
}]);
